### ISSUE TITLE
[bug] recipe stays on after closing

### ISSUE THREAD

**Issue by Inlife** [puruscor/Purus-Pasta#11]
Let's suppose you have current situation: you have opened recipe for bucket, you have 7 boards in inventory, you made 1 bucket, and closed recipe. Now, you are able to construct barrel with the rest of the boards, right? No, you cant do this because  the boards are staying highlighted with green even with closed recipe (and thus they're stay reserved).

I think problem related to feature with showing last 4 recipes. :/

Anyways, thank you :3

**Comment by puruscor** [comment]
Fixed
