### ISSUE TITLE
[error][pre-release] mussel picker exception

### ISSUE THREAD

**Issue by Inlife** [puruscor/Purus-Pasta#13]
Client version:  #[11d39a5](https://github.com/puruscor/Purus-Pasta/commit/11d39a58851bd3ce1ad6ed368bc8702b61e5a9b8)

After collecting the last mussel of several found mussels, script throws exception:

![image](https://cloud.githubusercontent.com/assets/2182108/14420041/67598d52-ffd2-11e5-9907-2dc0ca9602da.png)

Copy-pasted error text:
```
java.lang.NullPointerException
	at purus.MusselPicker$1.run(MusselPicker.java:73)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by puruscor** [comment]
Its known issue. If it cannot find mussels (mussels = null) it will throw
NPE. Something fancy could be added such as text: "No mussels found"
11.4.2016 11.36 ap. "Vladislav Gritsenko" <notifications@github.com>
kirjoitti:

**Comment by puruscor** [comment]
_Should_ be fixed now
