### ISSUE TITLE
Enable launch with -p flag

### ISSUE THREAD

**Issue by RichardVoid** [puruscor/Purus-Pasta#7]
For compatibility with  [Map Merger](http://www.havenandhearth.com/forum/viewtopic.php?f=49&t=43851&sid=4bbe8431d34f619cde500ecd25a12145)

**Comment by puruscor** [comment]
This is indeed possible. But you will have to use custom bat file to launch it with -p args.
Feature to do this with easy way might be added to launcher sometime. But for now you will have to use your own .bat.

**Comment by RichardVoid** [comment]
Thanks for answere
